FROM python:3.12-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api /app/api
COPY src /app/src
ENV PYTHONPATH=/app

EXPOSE 8000
CMD ["python", "/app/api/fridge_app.py"]